# install the runtime stack (python)
FROM python:3.12-slim

# prevent compatibility and buffer issues
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# install postgres dev libs, C compiler, libreoffice and fonts
RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev libreoffice-writer \
    fonts-dejavu fonts-liberation && rm -rf /var/lib/apt/lists/*

# set up the working directory
WORKDIR /app

# copy dependencies from app into docker image
COPY ../requirements.txt .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# copy app project into docker image container dir (WORKDIR /app)
COPY . /app

# expose port 8000
EXPOSE 8000

# set python env variable
ENV PYTHONPATH="/app:/app"

# run uvicorn server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "info"]
